-- MySQL Script generated by MySQL Workbench
-- ter 13 set 2022 08:22:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escolaridade` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoCivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoCivil` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filiacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filiacao` (
  `id` INT NOT NULL,
  `nome_pai` VARCHAR(100) NOT NULL,
  `nome_mae` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EsporteFavorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EsporteFavorito` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `id` INT NOT NULL,
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `Escolaridade_id` INT NOT NULL,
  `Sexo_id` INT NOT NULL,
  `EstadoCivil_id` INT NOT NULL,
  `Filiacao_id` INT NOT NULL,
  `EsporteFavorito_id` INT NOT NULL,
  PRIMARY KEY (`id`, `matricula`),
  INDEX `fk_Aluno_Escolaridade1_idx` (`Escolaridade_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Sexo1_idx` (`Sexo_id` ASC) VISIBLE,
  INDEX `fk_Aluno_EstadoCivil1_idx` (`EstadoCivil_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Filiacao1_idx` (`Filiacao_id` ASC) VISIBLE,
  INDEX `fk_Aluno_EsporteFavorito1_idx` (`EsporteFavorito_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Escolaridade1`
    FOREIGN KEY (`Escolaridade_id`)
    REFERENCES `mydb`.`Escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Sexo1`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `mydb`.`Sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id`)
    REFERENCES `mydb`.`EstadoCivil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Filiacao1`
    FOREIGN KEY (`Filiacao_id`)
    REFERENCES `mydb`.`Filiacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_EsporteFavorito1`
    FOREIGN KEY (`EsporteFavorito_id`)
    REFERENCES `mydb`.`EsporteFavorito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`País`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`País` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  `País_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UF_País1_idx` (`País_id` ASC) VISIBLE,
  CONSTRAINT `fk_UF_País1`
    FOREIGN KEY (`País_id`)
    REFERENCES `mydb`.`País` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `UF_id` INT NOT NULL,
  `DDD` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cidade_UF1_idx` (`UF_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_UF1`
    FOREIGN KEY (`UF_id`)
    REFERENCES `mydb`.`UF` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Bairro_Cidade_idx` (`Cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `mydb`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEndereco` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` INT NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `Bairro_id` INT NOT NULL,
  `TipoEndereco_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TipoEndereco_id`),
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_id` ASC) VISIBLE,
  INDEX `fk_Endereco_TipoEndereco1_idx` (`TipoEndereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_id`)
    REFERENCES `mydb`.`Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_TipoEndereco1`
    FOREIGN KEY (`TipoEndereco_id`)
    REFERENCES `mydb`.`TipoEndereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoTelefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoTelefone` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titulacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titulacao` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `id` INT NOT NULL,
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `Titulacao_id` INT NOT NULL,
  `Sexo_id` INT NOT NULL,
  `EstadoCivil_id` INT NOT NULL,
  `Filiacao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `matricula`),
  INDEX `fk_Professor_Titulacao1_idx` (`Titulacao_id` ASC) VISIBLE,
  INDEX `fk_Professor_Sexo1_idx` (`Sexo_id` ASC) VISIBLE,
  INDEX `fk_Professor_EstadoCivil1_idx` (`EstadoCivil_id` ASC) VISIBLE,
  INDEX `fk_Professor_Filiacao1_idx` (`Filiacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Titulacao1`
    FOREIGN KEY (`Titulacao_id`)
    REFERENCES `mydb`.`Titulacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Sexo1`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `mydb`.`Sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id`)
    REFERENCES `mydb`.`EstadoCivil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Filiacao1`
    FOREIGN KEY (`Filiacao_id`)
    REFERENCES `mydb`.`Filiacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id` INT NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `TipoTelefone_id` INT NOT NULL,
  `Aluno_id` INT NOT NULL,
  `Aluno_matricula` INT NOT NULL,
  `Cidade_id` INT NOT NULL,
  `Professor_id` INT NOT NULL,
  `Professor_matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefone_TipoTelefone1_idx` (`TipoTelefone_id` ASC) VISIBLE,
  INDEX `fk_Telefone_Aluno1_idx` (`Aluno_id` ASC, `Aluno_matricula` ASC) VISIBLE,
  INDEX `fk_Telefone_Cidade1_idx` (`Cidade_id` ASC) VISIBLE,
  INDEX `fk_Telefone_Professor1_idx` (`Professor_id` ASC, `Professor_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_TipoTelefone1`
    FOREIGN KEY (`TipoTelefone_id`)
    REFERENCES `mydb`.`TipoTelefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Aluno1`
    FOREIGN KEY (`Aluno_id` , `Aluno_matricula`)
    REFERENCES `mydb`.`Aluno` (`id` , `matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `mydb`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Professor1`
    FOREIGN KEY (`Professor_id` , `Professor_matricula`)
    REFERENCES `mydb`.`Professor` (`id` , `matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_has_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_has_Endereco` (
  `Aluno_id` INT NOT NULL,
  `Aluno_matricula` INT NOT NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`Aluno_id`, `Aluno_matricula`, `Endereco_id`),
  INDEX `fk_Aluno_has_Endereco_Endereco1_idx` (`Endereco_id` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Endereco_Aluno1_idx` (`Aluno_id` ASC, `Aluno_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Endereco_Aluno1`
    FOREIGN KEY (`Aluno_id` , `Aluno_matricula`)
    REFERENCES `mydb`.`Aluno` (`id` , `matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Endereco_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor_has_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor_has_Endereco` (
  `Professor_id` INT NOT NULL,
  `Professor_matricula` INT NOT NULL,
  `Endereco_id` INT NOT NULL,
  `Endereco_TipoEndereco_id` INT NOT NULL,
  PRIMARY KEY (`Professor_id`, `Professor_matricula`, `Endereco_id`, `Endereco_TipoEndereco_id`),
  INDEX `fk_Professor_has_Endereco_Endereco1_idx` (`Endereco_id` ASC, `Endereco_TipoEndereco_id` ASC) VISIBLE,
  INDEX `fk_Professor_has_Endereco_Professor1_idx` (`Professor_id` ASC, `Professor_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Endereco_Professor1`
    FOREIGN KEY (`Professor_id` , `Professor_matricula`)
    REFERENCES `mydb`.`Professor` (`id` , `matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Endereco_Endereco1`
    FOREIGN KEY (`Endereco_id` , `Endereco_TipoEndereco_id`)
    REFERENCES `mydb`.`Endereco` (`id` , `TipoEndereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `num_horas` INT NOT NULL,
  `num_vagas_total` INT NOT NULL,
  `nuym_vagas_ocupadas` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `Professor_id` INT NOT NULL,
  `Professor_matricula` INT NOT NULL,
  PRIMARY KEY (`id`, `codigo`),
  INDEX `fk_Curso_Professor1_idx` (`Professor_id` ASC, `Professor_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Professor1`
    FOREIGN KEY (`Professor_id` , `Professor_matricula`)
    REFERENCES `mydb`.`Professor` (`id` , `matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso_has_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso_has_Aluno` (
  `Curso_id` INT NOT NULL,
  `Curso_codigo` VARCHAR(45) NOT NULL,
  `Aluno_id` INT NOT NULL,
  `Aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`Curso_id`, `Curso_codigo`, `Aluno_id`, `Aluno_matricula`),
  INDEX `fk_Curso_has_Aluno_Aluno1_idx` (`Aluno_id` ASC, `Aluno_matricula` ASC) VISIBLE,
  INDEX `fk_Curso_has_Aluno_Curso1_idx` (`Curso_id` ASC, `Curso_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_has_Aluno_Curso1`
    FOREIGN KEY (`Curso_id` , `Curso_codigo`)
    REFERENCES `mydb`.`Curso` (`id` , `codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_id` , `Aluno_matricula`)
    REFERENCES `mydb`.`Aluno` (`id` , `matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
