-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 10:42:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AreaDeConhecimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AreaDeConhecimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AreaDeConhecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Editora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Editora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Livro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `isbn` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `num_paginas` INT NOT NULL,
  `ano_edicao` YEAR(4) NOT NULL,
  `AreaDeConhecimento_id` INT NOT NULL,
  `Editora_id` INT NOT NULL,
  `Autor_id` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_Livro_AreaDeConhecimento1_idx` (`AreaDeConhecimento_id` ASC) VISIBLE,
  INDEX `fk_Livro_Editora1_idx` (`Editora_id` ASC) VISIBLE,
  INDEX `fk_Livro_Autor1_idx` (`Autor_id` ASC) VISIBLE,
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_AreaDeConhecimento1`
    FOREIGN KEY (`AreaDeConhecimento_id`)
    REFERENCES `mydb`.`AreaDeConhecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Editora1`
    FOREIGN KEY (`Editora_id`)
    REFERENCES `mydb`.`Editora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Autor1`
    FOREIGN KEY (`Autor_id`)
    REFERENCES `mydb`.`Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titulacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Titulacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Titulacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sexo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UF` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `UF_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cidade_Uf_idx` (`UF_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Uf`
    FOREIGN KEY (`UF_id`)
    REFERENCES `mydb`.`UF` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `mydb`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEndereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoEndereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoEndereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NOT NULL,
  `Bairro_id` INT NOT NULL,
  `TipoEndereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_id` ASC) VISIBLE,
  INDEX `fk_Endereco_TipoEndereco1_idx` (`TipoEndereco_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_id`)
    REFERENCES `mydb`.`Bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_TipoEndereco1`
    FOREIGN KEY (`TipoEndereco_id`)
    REFERENCES `mydb`.`TipoEndereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoCivil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EstadoCivil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EstadoCivil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filiacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Filiacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Filiacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pai` VARCHAR(45) NULL,
  `mae` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoTelefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoTelefone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoTelefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(50) NOT NULL,
  `ddd` VARCHAR(5) NOT NULL,
  `TipoTelefone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefone_TipoTelefone1_idx` (`TipoTelefone_id` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_TipoTelefone1`
    FOREIGN KEY (`TipoTelefone_id`)
    REFERENCES `mydb`.`TipoTelefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Naturalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Naturalidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Naturalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `matricula` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_titulacao` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `carga_horaria` INT NULL,
  `Titulacao_id` INT NOT NULL,
  `Sexo_id` INT NOT NULL,
  `Endereco_id` INT NOT NULL,
  `EstadoCivil_id` INT NOT NULL,
  `Filiacao_id` INT NOT NULL,
  `Telefone_id` INT NOT NULL,
  `Naturalidade_id` INT NOT NULL,
  PRIMARY KEY (`matricula`, `cpf`),
  INDEX `fk_Professor_Titulacao1_idx` (`Titulacao_id` ASC) VISIBLE,
  INDEX `fk_Professor_Sexo1_idx` (`Sexo_id` ASC) VISIBLE,
  INDEX `fk_Professor_Endereco1_idx` (`Endereco_id` ASC) VISIBLE,
  INDEX `fk_Professor_EstadoCivil1_idx` (`EstadoCivil_id` ASC) VISIBLE,
  INDEX `fk_Professor_Filiacao1_idx` (`Filiacao_id` ASC) VISIBLE,
  INDEX `fk_Professor_Telefone1_idx` (`Telefone_id` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Professor_Naturalidade1_idx` (`Naturalidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Titulacao1`
    FOREIGN KEY (`Titulacao_id`)
    REFERENCES `mydb`.`Titulacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Sexo1`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `mydb`.`Sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id`)
    REFERENCES `mydb`.`EstadoCivil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Filiacao1`
    FOREIGN KEY (`Filiacao_id`)
    REFERENCES `mydb`.`Filiacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Telefone1`
    FOREIGN KEY (`Telefone_id`)
    REFERENCES `mydb`.`Telefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Naturalidade1`
    FOREIGN KEY (`Naturalidade_id`)
    REFERENCES `mydb`.`Naturalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deficiencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Deficiencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Deficiencia` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `matricula` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Sexo_id` INT NOT NULL,
  `Endereco_id` INT NOT NULL,
  `EstadoCivil_id` INT NOT NULL,
  `Filiacao_id` INT NOT NULL,
  `Telefone_id` INT NOT NULL,
  `Naturalidade_id` INT NOT NULL,
  `Deficiencia_id` INT NULL,
  PRIMARY KEY (`matricula`, `cpf`),
  INDEX `fk_Aluno_Sexo1_idx` (`Sexo_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Endereco1_idx` (`Endereco_id` ASC) VISIBLE,
  INDEX `fk_Aluno_EstadoCivil1_idx` (`EstadoCivil_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Filiacao1_idx` (`Filiacao_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Telefone1_idx` (`Telefone_id` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Aluno_Naturalidade1_idx` (`Naturalidade_id` ASC) VISIBLE,
  INDEX `fk_Aluno_Deficiencia1_idx` (`Deficiencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Sexo1`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `mydb`.`Sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id`)
    REFERENCES `mydb`.`EstadoCivil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Filiacao1`
    FOREIGN KEY (`Filiacao_id`)
    REFERENCES `mydb`.`Filiacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Telefone1`
    FOREIGN KEY (`Telefone_id`)
    REFERENCES `mydb`.`Telefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Naturalidade1`
    FOREIGN KEY (`Naturalidade_id`)
    REFERENCES `mydb`.`Naturalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Deficiencia1`
    FOREIGN KEY (`Deficiencia_id`)
    REFERENCES `mydb`.`Deficiencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HabilidadeEspecifica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HabilidadeEspecifica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HabilidadeEspecifica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CorDaPele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CorDaPele` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CorDaPele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `matricula` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `num_dependentes` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `HabilidadeEspecifica_id` INT NOT NULL,
  `Sexo_id` INT NOT NULL,
  `Endereco_id` INT NOT NULL,
  `EstadoCivil_id` INT NOT NULL,
  `Filiacao_id` INT NOT NULL,
  `Telefone_id` INT NOT NULL,
  `Naturalidade_id` INT NOT NULL,
  `CorDaPele_id` INT NOT NULL,
  PRIMARY KEY (`matricula`, `cpf`),
  INDEX `fk_Funcionario_HabilidadeEspecifica1_idx` (`HabilidadeEspecifica_id` ASC) VISIBLE,
  INDEX `fk_Funcionario_Sexo1_idx` (`Sexo_id` ASC) VISIBLE,
  INDEX `fk_Funcionario_Endereco1_idx` (`Endereco_id` ASC) VISIBLE,
  INDEX `fk_Funcionario_EstadoCivil1_idx` (`EstadoCivil_id` ASC) VISIBLE,
  INDEX `fk_Funcionario_Filiacao1_idx` (`Filiacao_id` ASC) VISIBLE,
  INDEX `fk_Funcionario_Telefone1_idx` (`Telefone_id` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Funcionario_Naturalidade1_idx` (`Naturalidade_id` ASC) VISIBLE,
  INDEX `fk_Funcionario_CorDaPele1_idx` (`CorDaPele_id` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_HabilidadeEspecifica1`
    FOREIGN KEY (`HabilidadeEspecifica_id`)
    REFERENCES `mydb`.`HabilidadeEspecifica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Sexo1`
    FOREIGN KEY (`Sexo_id`)
    REFERENCES `mydb`.`Sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id`)
    REFERENCES `mydb`.`EstadoCivil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Filiacao1`
    FOREIGN KEY (`Filiacao_id`)
    REFERENCES `mydb`.`Filiacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Telefone1`
    FOREIGN KEY (`Telefone_id`)
    REFERENCES `mydb`.`Telefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Naturalidade1`
    FOREIGN KEY (`Naturalidade_id`)
    REFERENCES `mydb`.`Naturalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_CorDaPele1`
    FOREIGN KEY (`CorDaPele_id`)
    REFERENCES `mydb`.`CorDaPele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Multa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Multa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Multa` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data_emitida` DATETIME NOT NULL DEFAULT NOW(),
  `foi_pago` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmprestimoProfessor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmprestimoProfessor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmprestimoProfessor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_emprestimo` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `Multa_codigo` INT NULL,
  `Livro_isbn` VARCHAR(45) NOT NULL,
  `Professor_matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Professor_has_Livro_Professor1_idx` (`Professor_matricula` ASC) VISIBLE,
  INDEX `fk_EmprestimoProfessor_Multa1_idx` (`Multa_codigo` ASC) VISIBLE,
  INDEX `fk_EmprestimoProfessor_Livro1_idx` (`Livro_isbn` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Livro_Professor1`
    FOREIGN KEY (`Professor_matricula`)
    REFERENCES `mydb`.`Professor` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmprestimoProfessor_Multa1`
    FOREIGN KEY (`Multa_codigo`)
    REFERENCES `mydb`.`Multa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmprestimoProfessor_Livro1`
    FOREIGN KEY (`Livro_isbn`)
    REFERENCES `mydb`.`Livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmprestimoAluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmprestimoAluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmprestimoAluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_emprestimo` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `Multa_codigo` INT NULL,
  `Aluno_matricula` INT NOT NULL,
  `Livro_isbn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Aluno_has_Livro_Aluno1_idx` (`Aluno_matricula` ASC) VISIBLE,
  INDEX `fk_EmprestimoAluno_Multa1_idx` (`Multa_codigo` ASC) VISIBLE,
  INDEX `fk_EmprestimoAluno_Livro1_idx` (`Livro_isbn` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Livro_Aluno1`
    FOREIGN KEY (`Aluno_matricula`)
    REFERENCES `mydb`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmprestimoAluno_Multa1`
    FOREIGN KEY (`Multa_codigo`)
    REFERENCES `mydb`.`Multa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmprestimoAluno_Livro1`
    FOREIGN KEY (`Livro_isbn`)
    REFERENCES `mydb`.`Livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmprestimoFuncionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmprestimoFuncionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmprestimoFuncionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_vencimento` DATE NOT NULL,
  `data_emprestimo` DATE NOT NULL,
  `Livro_isbn` VARCHAR(45) NOT NULL,
  `Funcionario_matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Funcionario_has_Livro_Funcionario1_idx` (`Funcionario_matricula` ASC) VISIBLE,
  INDEX `fk_EmprestimoFuncionario_Livro1_idx` (`Livro_isbn` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_has_Livro_Funcionario1`
    FOREIGN KEY (`Funcionario_matricula`)
    REFERENCES `mydb`.`Funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmprestimoFuncionario_Livro1`
    FOREIGN KEY (`Livro_isbn`)
    REFERENCES `mydb`.`Livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
